apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mymongo
        image: van133/mymongo
        ports:
        - containerPort : 27017
        volumeMounts:
        - name: mongo
          mountPath: /data/mongo
      volumes:
      - name: mongo
        emptyDir: {}


---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 27017
    targetPort: 27017