kind: Deployment
apiVersion: apps/v1
metadata:
  name: svelte
  labels:
    app: svelte
spec:
  replicas: 2
  selector:
    matchLabels:
      app: svelte
  template:
    metadata:
      labels:
        app: svelte
    spec:
      containers:
      - name: svelte
        image: van133/assignmet3_svelte
        ports:
        - containerPort: 80