kind: Deployment
apiVersion: apps/v1
metadata:
  name: svelte
  labels:
    app: svelte
spec:
  replicas: 2
  selector:
    matchLabels:
      app: svelte
  template:
    metadata:
      labels:
        app: svelte
    spec:
      containers:
      - name: svelte
        image: van133/assignment3_svelte
        ports:
        - containerPort: 80
---
apiVersion: v1                                         
kind: Service                                          
metadata:
  name: nodeport             
spec:
  type: NodePort                                       
  selector:
    app: svelte                       
  ports:                                                
  - port: 80
    targetPort: 80
    protocol: TCP